version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'check pr'
    validate:
      - do: title
        must_exclude:
          regex: 'wip|work in progress'

      - do: description
        no_empty:
          enabled: true
          message: Need to make a description of the pull request

      - do: approvals
        min:
          count: 1
        required:
          assignees: true
